disable merge pr

diff --git a/.github/workflows/github-terraform-fmt-check.yml b/.github/workflows/github-terraform-fmt-check.yml
--- a/.github/workflows/github-terraform-fmt-check.yml
+++ b/.github/workflows/github-terraform-fmt-check.yml
@@ -16,3 +16,9 @@ jobs:
     
     - name: terraform fmt check
       uses: dflook/terraform-fmt-check@v1
+      
+    - name: Run on Fail fmt
+      if: failure()
+      run: |
+        echo "fmt failed fix the terraform files"
+        exit 1
